### ISSUE TITLE
19年面试问题

### ISSUE THREAD

**Issue by TheGreatSummer** [nuaa-cs-kaoyan/nuaa-cs-kaoyan-share#1]
信封内的三道题
1.L1={ambn|m,n>=1}, L2={anbn|n>=1}  问这是什么编程语言
2.什么是算法  算法的精确定义是啥
3.heap与stack的区别  并举例表示

其余的问题：
1.用英语介绍UML是啥
2.CMMI是是什么的缩写
3.计算机网络中  有关介质之类的问题
... ...

**Comment by wansho** [comment]
收到
